services:
    - type: web
      name: toin
      env: python
      buildCommand: |
          pip install -r requirements.txt
          python manage.py collectstatic --noinput
      startCommand: gunicorn toin.wsgi:application
      envVars:
          - key: PYTHON_VERSION
            value: 3.11.x
          - key: DEBUG
            value: 'False'
          - key: SECRET_KEY
            value: 'your-secure-secret-key'
          - key: ALLOWED_HOSTS
            value: 'toin.onrender.com'
      headers:
          - path: /static/*
            headers:
                Cache-Control: public, max-age=31536000, immutable
                Content-Type:
                    - path: /static/fonts/*.woff
                      value: application/font-woff
                    - path: /static/fonts/*.woff2
                      value: font/woff2
                    - path: /static/*.css
                      value: text/css
                    - path: /static/*.js
                      value: application/javascript
