INSERT INTO
    pages_recruiter (
        en_title,
        vi_title,
        jp_title,
        en_description,
        vi_description,
        jp_description,
        en_requirements,
        vi_requirements,
        jp_requirements,
        en_benefits,
        vi_benefits,
        jp_benefits,
        salary_range,
        location,
        employment_type,
        experience_level,
        department,
        is_active
    )
VALUES (
        'Production Engineer',
        'Kỹ sư Sản xuất',
        '生産エンジニア',
        'Responsible for overseeing manufacturing processes, ensuring quality control, and optimizing production efficiency at our Vietnam factory.',
        'Chịu trách nhiệm giám sát quy trình sản xuất, đảm bảo kiểm soát chất lượng và tối ưu hóa hiệu suất sản xuất tại nhà máy Việt Nam.',
        'ベトナム工場での製造プロセスの監督、品質管理、生産効率の最適化を担当します。',
        '• Bachelor''s degree in Mechanical/Industrial Engineering\n• 2+ years manufacturing experience\n• Knowledge of Lean Manufacturing\n• English proficiency required\n• Familiarity with Japanese quality standards',
        '• Cử nhân Kỹ thuật Cơ khí/Công nghiệp\n• 2+ năm kinh nghiệm sản xuất\n• Hiểu biết về Lean Manufacturing\n• Thành thạo tiếng Anh\n• Quen thuộc với tiêu chuẩn chất lượng Nhật Bản',
        '• 機械工学/工業工学の学士号\n• 製造業2年以上の経験\n• リーン生産方式の知識\n• 英語力必須\n• 日本品質基準の理解',
        '• Competitive salary + performance bonus\n• Japanese standard benefits\n• Annual health checkup\n• 15 days annual leave\n• Professional training opportunities',
        '• Mức lương cạnh tranh + thưởng hiệu suất\n• Chế độ phúc lợi chuẩn Nhật\n• Kiểm tra sức khỏe hàng năm\n• 15 ngày phép/năm\n• Cơ hội đào tạo chuyên môn',
        '• 競争力のある給与+業績ボーナス\n• 日本基準の福利厚生\n• 年間健康診断\n• 年15日の有給休暇\n• 専門トレーニング機会',
        '15-25M VND',
        'Bình Dương, Vietnam',
        'FULL_TIME',
        'MID',
        'Production',
        TRUE
    ),
    (
        'Quality Control Supervisor',
        'Giám sát Kiểm soát Chất lượng',
        '品質管理監督者',
        'Lead the quality assurance team to maintain Japanese manufacturing standards and ensure product quality meets international requirements.',
        'Dẫn dắt đội ngũ đảm bảo chất lượng để duy trì tiêu chuẩn sản xuất Nhật Bản và đảm bảo sản phẩm đạt yêu cầu quốc tế.',
        '品質保証チームを率い、日本製造基準を維持し、製品品質が国際基準を満たすことを確保します。',
        '• Bachelor''s in Quality Management\n• 3+ years QA/QC experience\n• ISO 9001 certification preferred\n• Strong analytical skills\n• Japanese language bonus',
        '• Cử nhân Quản lý Chất lượng\n• 3+ năm kinh nghiệm QA/QC\n• Chứng chỉ ISO 9001 ưu tiên\n• Kỹ năng phân tích tốt\n• Tiếng Nhật là lợi thế',
        '• 品質管理の学士号\n• QA/QC経験3年以上\n• ISO 9001認証優遇\n• 強い分析力\n• 日本語力加点',
        '• Salary 20-30M VND + bonus\n• Company car for supervisors\n• 5 social insurances\n• Annual Japan training trip\n• Promotion opportunities',
        '• Lương 20-30M + thưởng\n• Xe công ty cho quản lý\n• 5 loại bảo hiểm\n• Chuyến đào tạo Nhật Bản hàng năm\n• Cơ hội thăng tiến',
        '• 給与20-30M VND+ボーナス\n• 管理職向け社用車\n• 5つの社会保険\n• 年間日本研修旅行\n• 昇進機会',
        '20-30M VND',
        'Bình Dương, Vietnam',
        'FULL_TIME',
        'SENIOR',
        'Quality Control',
        TRUE
    ),
    (
        'Sales Executive - Export',
        'Nhân viên Kinh doanh Xuất khẩu',
        '輸出営業担当',
        'Develop and maintain relationships with international clients, focusing on export markets in Asia and Europe.',
        'Phát triển và duy trì quan hệ với khách hàng quốc tế, tập trung vào thị trường xuất khẩu châu Á và châu Âu.',
        'アジア・ヨーロッパ輸出市場に焦点を当て、国際顧客との関係を構築・維持します。',
        '• Bachelor''s in Business/International Trade\n• 1+ year sales experience\n• English fluency required\n• Japanese language advantage\n• Willing to travel',
        '• Cử nhân Kinh doanh/Thương mại Quốc tế\n• 1+ năm kinh nghiệm bán hàng\n• Thành thạo tiếng Anh\n• Tiếng Nhật là lợi thế\n• Sẵn sàng đi công tác',
        '• ビジネス/国際貿易の学士号\n• 営業経験1年以上\n• 英語流暢必須\n• 日本語優遇\n• 出張可能',
        '• Base 12-18M + sales commission\n• Overseas travel allowance\n• Company laptop & phone\n• 13th month salary\n• Annual sales awards',
        '• Lương cơ bản 12-18M + hoa hồng\n• Trợ cấp đi công tác nước ngoài\n• Laptop & điện thoại công ty\n• Lương tháng 13\n• Giải thưởng bán hàng hàng năm',
        '• 基本給12-18M+営業手当\n• 海外出張手当\n• 会社支給PC&携帯\n• 13ヶ月目給与\n• 年間営業表彰',
        '12-18M + Commission',
        'HCMC Head Office',
        'FULL_TIME',
        'JUNIOR',
        'Sales',
        TRUE
    ),
    (
        'HR & Admin Staff',
        'Nhân viên Hành chính Nhân sự',
        '人事・管理スタッフ',
        'Support HR operations including recruitment, employee relations, and office administration for our growing Vietnam team.',
        'Hỗ trợ hoạt động nhân sự bao gồm tuyển dụng, quan hệ nhân viên và hành chính văn phòng cho đội ngũ Việt Nam đang phát triển.',
        '成長中のベトナムチーム向けに、採用、従業員関係、文書管理を含む人事業務をサポートします。',
        '• Bachelor''s in HR Management\n• 1+ year HR/admin experience\n• Good English communication\n• MS Office proficiency\n• Detail-oriented',
        '• Cử nhân Quản trị Nhân sự\n• 1+ năm kinh nghiệm HR/hành chính\n• Giao tiếp tiếng Anh tốt\n• Thành thạo MS Office\n• Cẩn thận chi tiết',
        '• 人事管理の学士号\n• HR/管理経験1年以上\n• 英語コミュニケーション力\n• MS Office熟練\n• 細部に注意',
        '• Salary 10-15M VND\n• Full social insurances\n• Annual company trip\n• Birthday gifts\n• Training sponsorship',
        '• Lương 10-15M\n• Đầy đủ bảo hiểm\n• Du lịch công ty hàng năm\n• Quà sinh nhật\n• Tài trợ đào tạo',
        '• 給与10-15M VND\n• 社会保険完備\n• 年間社員旅行\n• 誕生日プレゼント\n• 研修費補助',
        '10-15M VND',
        'HCMC Head Office',
        'FULL_TIME',
        'ENTRY',
        'HR & Admin',
        TRUE
    ),
    (
        'IT Support Specialist',
        'Chuyên viên Hỗ trợ CNTT',
        'ITサポートスペシャリスト',
        'Provide technical support for factory systems, network maintenance, and ERP implementation across all Vietnam locations.',
        'Cung cấp hỗ trợ kỹ thuật cho hệ thống nhà máy, bảo trì mạng và triển khai ERP tại tất cả địa điểm Việt Nam.',
        'ベトナム全拠点での工場システム技術サポート、ネットワーク保守、ERP導入を担当します。',
        '• Bachelor''s in IT/Computer Science\n• 2+ years IT support experience\n• ERP system knowledge\n• Network troubleshooting\n• English required',
        '• Cử nhân CNTT/Khoa học Máy tính\n• 2+ năm kinh nghiệm hỗ trợ CNTT\n• Hiểu biết hệ thống ERP\n• Xử lý sự cố mạng\n• Tiếng Anh bắt buộc',
        '• IT/コンピュータサイエンスの学士号\n• ITサポート経験2年以上\n• ERPシステム知識\n• ネットワークトラブルシューティング\n• 英語必須',
        '• Salary 15-22M VND\n• Laptop & IT equipment\n• 24/7 technical training\n• On-call allowance\n• Performance bonus',
        '• Lương 15-22M\n• Laptop & thiết bị CNTT\n• Đào tạo kỹ thuật 24/7\n• Trợ cấp trực\n• Thưởng hiệu suất',
        '• 給与15-22M VND\n• ノートPC&IT機器支給\n• 24/7技術研修\n• オンコール手当\n• 業績ボーナス',
        '15-22M VND',
        'Bình Dương, Vietnam',
        'FULL_TIME',
        'MID',
        'IT Department',
        TRUE
    );