# Generated by Django 5.2.7 on 2025-10-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='intro/')),
            ],
            options={
                'verbose_name': 'Introduction',
                'verbose_name_plural': 'Introduction',
            },
        ),
    ]
