# Generated by Django 5.2.7 on 2025-10-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_business_description_remove_business_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('foundation_date', models.DateField()),
                ('representative', models.CharField(max_length=100)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('productions_operations', models.TextField()),
                ('address', models.TextField()),
                ('parent_corporation', models.CharField(max_length=200)),
                ('parent_corporation_website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('en_description', models.TextField(blank=True, null=True)),
                ('vi_description', models.TextField(blank=True, null=True)),
                ('jp_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_title', models.CharField(blank=True, max_length=200, null=True)),
                ('vi_title', models.CharField(blank=True, max_length=200, null=True)),
                ('jp_title', models.CharField(blank=True, max_length=200, null=True)),
                ('en_description', models.TextField(blank=True, null=True)),
                ('vi_description', models.TextField(blank=True, null=True)),
                ('jp_description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_title', models.CharField(blank=True, max_length=200, null=True)),
                ('vi_title', models.CharField(blank=True, max_length=200, null=True)),
                ('jp_title', models.CharField(blank=True, max_length=200, null=True)),
                ('en_description', models.TextField(blank=True, null=True)),
                ('vi_description', models.TextField(blank=True, null=True)),
                ('jp_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
