# Generated by Django 5.2.7 on 2025-10-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_companyprofile_history_product_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='parent_corporation',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='productions_operations',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='en_address',
            field=models.TextField(default='No Data'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='en_parent_corporation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='en_productions_operations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='jp_address',
            field=models.TextField(default='No Data'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='jp_parent_corporation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='jp_productions_operations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='vi_address',
            field=models.TextField(default='No Data'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='vi_parent_corporation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='vi_productions_operations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
