# Generated by Django 5.2.7 on 2025-10-06 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_companyprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='en_parent_corporation',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='jp_parent_corporation',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='parent_corporation_website',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='vi_parent_corporation',
        ),
        migrations.CreateModel(
            name='ParentCorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vi_name', models.CharField(blank=True, max_length=200, null=True)),
                ('jp_name', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_corporations', to='pages.companyprofile')),
            ],
        ),
    ]
