# Generated by Django 5.2.7 on 2025-10-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_companyprofile_en_parent_corporation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='en_mission',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='jp_mission',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='vi_mission',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
