# Generated by Django 5.2.7 on 2025-10-07 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_companyprofile_en_mission_companyprofile_jp_mission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vi_name', models.CharField(blank=True, max_length=200, null=True)),
                ('jp_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address_link', models.URLField(blank=True, null=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_addresses', to='pages.companyprofile')),
            ],
        ),
    ]
