# Generated by Django 5.2.7 on 2025-10-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='en_address',
            field=models.TextField(default='No Data'),
        ),
        migrations.AddField(
            model_name='address',
            name='jp_address',
            field=models.TextField(default='No Data'),
        ),
        migrations.AddField(
            model_name='address',
            name='vi_address',
            field=models.TextField(default='No Data'),
        ),
    ]
