# Generated by Django 5.2.7 on 2025-10-07 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_address_en_address_address_jp_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parentcorporation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('contact_name', models.CharField(default='No Data', max_length=200)),
                ('contact_number', models.CharField(default='No Data', max_length=200)),
                ('contact_email', models.CharField(default='No Data', max_length=200)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_addresses', to='pages.address')),
            ],
        ),
    ]
