# Generated by Django 5.2.7 on 2025-10-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_address_id_alter_companyprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
