# Generated by Django 5.2.7 on 2025-10-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_address_address_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='feature/'),
        ),
    ]
