# Generated by Django 5.2.7 on 2025-10-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
