# Generated by Django 5.2.7 on 2025-10-08 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_feature_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_title', models.CharField(blank=True, max_length=200, null=True)),
                ('vi_title', models.CharField(blank=True, max_length=200, null=True)),
                ('jp_title', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('C', 'Cosmetics'), ('P', 'Pharmaceuticals'), ('F', 'Food'), ('D', 'Daily Necessities'), ('L', 'Labels'), ('I', 'Instructions')], default='C', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pages.type'),
        ),
    ]
