# Generated by Django 5.2.7 on 2025-10-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_type_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('P', 'Packages'), ('L', 'Labels'), ('I', 'Instructions'), ('T', 'Technologies')], default='P', max_length=1),
        ),
    ]
