# Generated by Django 5.2.7 on 2025-10-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vi_name', models.CharField(blank=True, max_length=200, null=True)),
                ('jp_name', models.CharField(blank=True, max_length=200, null=True)),
                ('en_description', models.TextField(blank=True, null=True)),
                ('vi_description', models.TextField(blank=True, null=True)),
                ('jp_description', models.TextField(blank=True, null=True)),
                ('en_address', models.TextField(blank=True, null=True)),
                ('vi_address', models.TextField(blank=True, null=True)),
                ('jp_address', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='partner/')),
            ],
        ),
    ]
