# Generated by Django 5.2.7 on 2025-10-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_title', models.CharField(blank=True, max_length=200, null=True)),
                ('vi_title', models.CharField(blank=True, max_length=200, null=True)),
                ('jp_title', models.CharField(blank=True, max_length=200, null=True)),
                ('en_description', models.TextField(blank=True, null=True)),
                ('vi_description', models.TextField(blank=True, null=True)),
                ('jp_description', models.TextField(blank=True, null=True)),
                ('en_requirements', models.TextField(blank=True, null=True)),
                ('vi_requirements', models.TextField(blank=True, null=True)),
                ('jp_requirements', models.TextField(blank=True, null=True)),
                ('en_benefits', models.TextField(blank=True, null=True)),
                ('vi_benefits', models.TextField(blank=True, null=True)),
                ('jp_benefits', models.TextField(blank=True, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship')], default='FULL_TIME', max_length=20)),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry Level'), ('JUNIOR', 'Junior'), ('MID', 'Mid Level'), ('SENIOR', 'Senior'), ('LEAD', 'Lead')], default='ENTRY', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='recruiter/')),
            ],
        ),
    ]
