# Generated by Django 5.2.7 on 2025-10-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
