# Generated by Django 5.2.7 on 2025-10-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_partner_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
