# Generated by Django 5.2.7 on 2025-10-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_recruiter_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('applicant_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('position_applied', models.CharField(blank=True, max_length=200, null=True, verbose_name='Position Applied For')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='Cover Letter')),
                ('cv_file', models.FileField(upload_to='cv_submissions/', verbose_name='CV/Resume File')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
            ],
            options={
                'verbose_name': 'CV Submission',
                'verbose_name_plural': 'CV Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
